version: '3'

services:

  coreweb:
    container_name: coreweb
    image: corewebimage
    build:
      context: ./publish
      dockerfile: Dockerfile
    environment:
      #- ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=Asia/Shanghai
    restart: always

  corewebproxy:
    container_name: corewebproxy
    image: nginx    
    ports:
      - "9090:9090"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    links:
      - coreweb
